apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  name: spring-ai-chat
spec:
  acceptedServiceBindings:
  - name: vector
    types:
    - postgresql
  build:
    buildpacks: {}
    nonSecretEnv:
    - name: BP_JVM_VERSION
      value: "17"
    path: ../..
  ports:
  - name: main
    port: 8080
  replicas: 0
